# ELARA Pipeline
Multi-label identity state classifier trained on declassified CIA/DARPA consciousness research.
Maps documents across 4 layers: memory · belief · emotion · behavior

In [1]:
# @title GitHub Secret <> Colab
from google.colab import userdata
import os

GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
GITHUB_USER = "LeiaAnapaula"
GITHUB_EMAIL = "leiaanapaula@berkeley.edu"
REPO_NAME = "elara"

!git config --global user.email "{GITHUB_EMAIL}"
!git config --global user.name "{GITHUB_USER}"

# Clone fresh into /content/elara
os.chdir("/content")
!git clone https://{GITHUB_USER}:{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{REPO_NAME}.git
os.chdir("/content/elara")

!mkdir -p 01_problem 02_data 03_features 04_training 05_evaluation 06_deployment

print("✓ Now in:", os.getcwd())
print("✓ Contents:", os.listdir("."))

Cloning into 'elara'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 19 (delta 2), reused 9 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (19/19), 310.13 KiB | 4.03 MiB/s, done.
Resolving deltas: 100% (2/2), done.
✓ Now in: /content/elara
✓ Contents: ['04_training', 'README.md', '06_deployment', '03_features', '02_data', 'LICENSE', '01_problem', '.git', '05_evaluation']

In [2]:
# Install dependencies
!pip install sentence-transformers scikit-learn pandas numpy umap-learn matplotlib seaborn -q

In [3]:
# Seed corpus

import pandas as pd

docs = [
    "Soldiers under fire showed impaired working memory and tunnel vision during combat operations",
    "Athletes in flow states report loss of self-consciousness and time distortion during peak performance",
    "Repeated trauma exposure alters threat appraisal thresholds permanently in combat veterans",
    "Sleep deprivation collapses decision quality and risk assessment after 18 hours of sustained operations",
    "Childhood attachment patterns anchor adult self-concept and identity under extreme stress",
    "Subjects exposed to prolonged isolation developed systematic distortions in self-referential thinking",
    "Hypervigilance states consume working memory capacity leaving fewer resources for executive function",
    "Operatives trained in resistance techniques showed altered fear consolidation compared to controls",
    "Meditation practitioners demonstrate measurable suppression of default mode network activity",
    "Extreme fatigue produces behavioral automaticity replacing conscious deliberation with habit execution",
    "Near death experiences produce lasting restructuring of core identity beliefs and meaning systems",
    "Sensory deprivation accelerates suggestibility and dissolution of self-concept boundaries",
    "High stakes decision makers under time pressure revert to pattern recognition over analytical reasoning",
    "Trauma survivors exhibit altered encoding of threat-relevant stimuli compared to neutral stimuli",
    "Elite performers describe pre-competition states as identity contraction toward a single purpose",
    "Chronic stress exposure produces lasting changes in emotional regulation circuitry and baseline arousal",
    "Subjects under enhanced interrogation showed dissociation as primary psychological defense mechanism",
    "Peak performance states in special operations correlate with suppression of self-monitoring cognition",
    "Long term meditators show structural changes in regions governing emotional reactivity and self-reference",
    "Behavioral breakdown under extreme duress follows predictable sequence: cognition, emotion, motor control"
]

labels = [
    ["Encoding Under Stress", "Threat Appraisal", "Fear & Threat Response", "Decision Under Duress"],
    ["Encoding Under Stress", "Self-Concept Updating", "Flow & Absorption", "Peak Performance Ceiling"],
    ["Traumatic Consolidation", "Threat Appraisal", "Fear & Threat Response", "Behavioral Breakdown"],
    ["Encoding Under Stress", "Threat Appraisal", "Stress & Arousal Regulation", "Decision Under Duress"],
    ["Identity Anchoring", "Self-Concept Updating", "Emotional Dysregulation", "Habit & Automaticity"],
    ["Identity Anchoring", "Cognitive Bias Formation", "Emotional Dysregulation", "Behavioral Breakdown"],
    ["Encoding Under Stress", "Threat Appraisal", "Stress & Arousal Regulation", "Decision Under Duress"],
    ["Traumatic Consolidation", "Self-Concept Updating", "Fear & Threat Response", "Habit & Automaticity"],
    ["Identity Anchoring", "Self-Concept Updating", "Flow & Absorption", "Habit & Automaticity"],
    ["Encoding Under Stress", "Cognitive Bias Formation", "Stress & Arousal Regulation", "Habit & Automaticity"],
    ["Identity Anchoring", "Meaning Construction", "Emotional Dysregulation", "Behavioral Breakdown"],
    ["Traumatic Consolidation", "Self-Concept Updating", "Emotional Dysregulation", "Behavioral Breakdown"],
    ["Encoding Under Stress", "Threat Appraisal", "Stress & Arousal Regulation", "Decision Under Duress"],
    ["Traumatic Consolidation", "Threat Appraisal", "Fear & Threat Response", "Behavioral Breakdown"],
    ["Identity Anchoring", "Self-Concept Updating", "Flow & Absorption", "Peak Performance Ceiling"],
    ["Traumatic Consolidation", "Threat Appraisal", "Stress & Arousal Regulation", "Behavioral Breakdown"],
    ["Traumatic Consolidation", "Self-Concept Updating", "Emotional Dysregulation", "Behavioral Breakdown"],
    ["Identity Anchoring", "Self-Concept Updating", "Flow & Absorption", "Peak Performance Ceiling"],
    ["Identity Anchoring", "Meaning Construction", "Flow & Absorption", "Habit & Automaticity"],
    ["Traumatic Consolidation", "Threat Appraisal", "Emotional Dysregulation", "Behavioral Breakdown"]
]

df = pd.DataFrame({"text": docs, "labels": labels})
df.to_csv("02_data/seed_corpus.csv", index=False)
print(f"Corpus saved — {len(df)} documents")
df.head(3)

Corpus saved — 20 documents

,text,labels
0,Soldiers under fire showed impaired working me...,"[Encoding Under Stress, Threat Appraisal, Fear..."
1,Athletes in flow states report loss of self-co...,"[Encoding Under Stress, Self-Concept Updating,..."
2,Repeated trauma exposure alters threat apprais...,"[Traumatic Consolidation, Threat Appraisal, Fe..."

In [4]:
# SPECTER Embed

from sentence_transformers import SentenceTransformer
import numpy as np

print("Loading SPECTER — scientific domain embeddings...")
model = SentenceTransformer("allenai-specter")

print("Embedding documents...")
X = model.encode(df["text"].tolist(), show_progress_bar=True)

np.save("03_features/specter_embeddings.npy", X)
print(f"Embeddings shape: {X.shape}")  # should be (20, 768)

Loading SPECTER — scientific domain embeddings...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/622 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/allenai-specter
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/331 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding documents...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embeddings shape: (20, 768)

In [5]:
# Multi-label binarize + train
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import ast

mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(df["labels"])

print(f"Labels shape: {Y.shape}")
print(f"All classes:\n{list(mlb.classes_)}")

# 60/20/20 split
X_train, X_temp, Y_train, Y_temp = train_test_split(X, Y, test_size=0.4, random_state=42)
X_dev, X_test, Y_dev, Y_test = train_test_split(X_temp, Y_temp, test_size=0.5, random_state=42)

print(f"\nTrain: {len(X_train)} · Dev: {len(X_dev)} · Test: {len(X_test)}")

# Train
clf = OneVsRestClassifier(LogisticRegression(max_iter=1000))
clf.fit(X_train, Y_train)
print("\nModel trained.")

Labels shape: (20, 15)
All classes:
['Behavioral Breakdown', 'Cognitive Bias Formation', 'Decision Under Duress', 'Emotional Dysregulation', 'Encoding Under Stress', 'Fear & Threat Response', 'Flow & Absorption', 'Habit & Automaticity', 'Identity Anchoring', 'Meaning Construction', 'Peak Performance Ceiling', 'Self-Concept Updating', 'Stress & Arousal Regulation', 'Threat Appraisal', 'Traumatic Consolidation']

Train: 12 · Dev: 4 · Test: 4

Model trained.

In [6]:
# @title More datasets

# 1   PubMed ~200 docs

!pip install biopython -q
from Bio import Entrez
import pandas as pd
import time

Entrez.email = "your@email.com"  # ← change this

queries = [
    "cognitive performance stress military",
    "fear memory consolidation trauma",
    "decision making cognitive load",
    "flow state peak performance psychology",
    "identity self-concept threat",
    "emotional regulation arousal",
    "dissociation psychological defense",
    "hypervigilance attention threat",
    "habit automaticity behavior",
    "meaning making identity crisis"
]

pubmed_docs = []

for query in queries:
    # Search
    handle = Entrez.esearch(db="pubmed", term=query, retmax=25)
    record = Entrez.read(handle)
    ids = record["IdList"]

    # Fetch abstracts
    handle = Entrez.efetch(db="pubmed", id=ids, rettype="abstract", retmode="text")
    abstracts = handle.read().split("\n\n")

    for abstract in abstracts:
        abstract = abstract.strip()
        if len(abstract) > 100:
            pubmed_docs.append({
                "text": abstract,
                "source": "PubMed",
                "query": query
            })

    print(f"✓ '{query}' → {len(ids)} docs")
    time.sleep(0.4)

df_pubmed = pd.DataFrame(pubmed_docs)
df_pubmed.to_csv("02_data/pubmed_raw.csv", index=False)
print(f"\n✓ PubMed total: {len(df_pubmed)} documents")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 24.3 MB/s eta 0:00:00
✓ 'cognitive performance stress military' → 25 docs
✓ 'fear memory consolidation trauma' → 25 docs
✓ 'decision making cognitive load' → 25 docs
✓ 'flow state peak performance psychology' → 25 docs
✓ 'identity self-concept threat' → 25 docs
✓ 'emotional regulation arousal' → 25 docs
✓ 'dissociation psychological defense' → 25 docs
✓ 'hypervigilance attention threat' → 25 docs
✓ 'habit automaticity behavior' → 25 docs
✓ 'meaning making identity crisis' → 24 docs

✓ PubMed total: 923 documents

In [7]:
# DTIC / DARPA (~ 150 docs)
import requests
import pandas as pd
import time

queries = [
    "human performance under stress",
    "cognitive performance degradation combat",
    "decision making under duress military",
    "psychological resilience training soldiers",
    "attention arousal military operations",
    "memory consolidation threat response",
    "behavioral breakdown extreme conditions",
    "identity stability under pressure",
    "peak performance special operations",
    "fear conditioning resistance training"
]

dtic_docs = []

for query in queries:
    url = "https://api.dtic.mil/api/v2/search/documents"
    params = {
        "q": query,
        "rows": 20,
        "fields": "title,abstract,sourceCollection,publicationDate"
    }

    try:
        r = requests.get(url, params=params, timeout=10)
        data = r.json()
        docs = data.get("response", {}).get("docs", [])

        for doc in docs:
            abstract = doc.get("abstract", "")
            if abstract and len(abstract) > 100:
                dtic_docs.append({
                    "text": abstract,
                    "title": doc.get("title", ""),
                    "source": "DTIC/DARPA",
                    "date": doc.get("publicationDate", ""),
                    "query": query
                })

        print(f"✓ '{query}' → {len(docs)} docs")
        time.sleep(0.5)

    except Exception as e:
        print(f"✗ '{query}' → {e}")

df_dtic = pd.DataFrame(dtic_docs)
df_dtic.to_csv("02_data/dtic_raw.csv", index=False)
print(f"\n✓ DTIC total: {len(df_dtic)} documents")

✗ 'human performance under stress' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=human+performance+under+stress&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af0534dbf20>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'cognitive performance degradation combat' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=cognitive+performance+degradation+combat&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af00c1c28d0>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'decision making under duress military' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=decision+making+under+duress+military&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af00c1c3950>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'psychological resilience training soldiers' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=psychological+resilience+training+soldiers&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af00c132180>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'attention arousal military operations' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=attention+arousal+military+operations&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af00c131370>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'memory consolidation threat response' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=memory+consolidation+threat+response&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7aefe7f53f80>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'behavioral breakdown extreme conditions' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=behavioral+breakdown+extreme+conditions&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af00c1c3e60>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'identity stability under pressure' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=identity+stability+under+pressure&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af00c1c3050>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'peak performance special operations' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=peak+performance+special+operations&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af00c1303b0>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))
✗ 'fear conditioning resistance training' → HTTPSConnectionPool(host='api.dtic.mil', port=443): Max retries exceeded with url: /api/v2/search/documents?q=fear+conditioning+resistance+training&rows=20&fields=title%2Cabstract%2CsourceCollection%2CpublicationDate (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7af00c131e80>: Failed to resolve 'api.dtic.mil' ([Errno -2] Name or service not known)"))

✓ DTIC total: 0 documents

In [8]:
# HuggingFace psychology datasets

from datasets import load_dataset
import pandas as pd

hf_docs = []

# Dataset 1 — mental health / psychological research corpus
try:
    ds1 = load_dataset("google-research-datasets/go_emotions", split="train[:300]")
    # Too short individually — skip, move to next
    print("go_emotions loaded but texts too short — skipping")
except:
    pass

# Dataset 2 — scientific abstracts (psychology subset)
try:
    ds2 = load_dataset("allenai/scirepeval", "psychology", split="train[:200]", trust_remote_code=True)
    for item in ds2:
        text = item.get("abstract", "") or item.get("text", "")
        if text and len(text) > 100:
            hf_docs.append({"text": text, "source": "HuggingFace/SciRepEval"})
    print(f"✓ SciRepEval psychology: {len(hf_docs)} docs")
except Exception as e:
    print(f"SciRepEval: {e}")

# Dataset 3 — psychology papers
try:
    ds3 = load_dataset("arXiv-psychology", split="train[:200]", trust_remote_code=True)
    for item in ds3:
        text = item.get("abstract", "")
        if text and len(text) > 100:
            hf_docs.append({"text": text, "source": "arXiv-psychology"})
    print(f"✓ arXiv psychology added")
except Exception as e:
    print(f"arXiv: {e}")

df_hf = pd.DataFrame(hf_docs)
df_hf.to_csv("02_data/huggingface_raw.csv", index=False)
print(f"\n✓ HuggingFace total: {len(df_hf)} documents")

README.md: 0.00B [00:00, ?B/s]

simplified/train-00000-of-00001.parquet:   0%|          | 0.00/2.77M [00:00<?, ?B/s]

simplified/validation-00000-of-00001.par(…):   0%|          | 0.00/350k [00:00<?, ?B/s]

simplified/test-00000-of-00001.parquet:   0%|          | 0.00/347k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/43410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5426 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5427 [00:00<?, ? examples/s]

`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'allenai/scirepeval' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
ERROR:datasets.load:`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'allenai/scirepeval' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

go_emotions loaded but texts too short — skipping

README.md: 0.00B [00:00, ?B/s]

`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'arXiv-psychology' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
ERROR:datasets.load:`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'arXiv-psychology' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

SciRepEval: BuilderConfig 'psychology' not found. Available: ['biomimicry', 'cite_count', 'cite_prediction', 'cite_prediction_aug2023refresh', 'cite_prediction_new', 'drsm', 'fos', 'high_influence_cite', 'mesh_descriptors', 'nfcorpus', 'paper_reviewer_matching', 'peer_review_score_hIndex', 'pub_year', 'relish', 'same_author', 'scidocs_mag_mesh', 'scidocs_view_cite_read', 'search', 'trec_covid', 'tweet_mentions']
arXiv: Dataset 'arXiv-psychology' doesn't exist on the Hub or cannot be accessed.

✓ HuggingFace total: 0 documents

In [9]:
# Merge Everything

import pandas as pd
import os

frames = []

# Seed corpus (your 20)
df_seed = pd.read_csv("02_data/seed_corpus.csv")
df_seed["source"] = "seed"
frames.append(df_seed[["text", "source"]])
print(f"Seed: {len(df_seed)}")

# PubMed
if os.path.exists("02_data/pubmed_raw.csv"):
    df_p = pd.read_csv("02_data/pubmed_raw.csv")
    if len(df_p) > 0:
        frames.append(df_p[["text", "source"]])
        print(f"PubMed: {len(df_p)}")

# DTIC — skip if empty
if os.path.exists("02_data/dtic_raw.csv"):
    try:
        df_d = pd.read_csv("02_data/dtic_raw.csv")
        if len(df_d) > 0:
            frames.append(df_d[["text", "source"]])
            print(f"DTIC: {len(df_d)}")
    except Exception as e:
        print(f"DTIC skipped — {e}")

# HuggingFace
if os.path.exists("02_data/huggingface_raw.csv"):
    try:
        df_h = pd.read_csv("02_data/huggingface_raw.csv")
        if len(df_h) > 0:
            frames.append(df_h[["text", "source"]])
            print(f"HuggingFace: {len(df_h)}")
    except Exception as e:
        print(f"HuggingFace skipped — {e}")

# Merge + clean
df_corpus = pd.concat(frames, ignore_index=True)
df_corpus = df_corpus[df_corpus["text"].notna()]
df_corpus = df_corpus[df_corpus["text"].str.len() > 80]
df_corpus = df_corpus.drop_duplicates(subset="text")
df_corpus = df_corpus.reset_index(drop=True)

df_corpus.to_csv("02_data/elara_corpus_raw.csv", index=False)
print(f"\n✓ TOTAL CORPUS: {len(df_corpus)} documents")
print(f"  By source:\n{df_corpus['source'].value_counts()}")

Seed: 20
PubMed: 923
DTIC skipped — No columns to parse from file
HuggingFace skipped — No columns to parse from file

✓ TOTAL CORPUS: 917 documents
  By source:
source
PubMed    897
seed       20
Name: count, dtype: int64

In [10]:
# Evaluate

Y_pred = clf.predict(X_dev)
print("=== DEV SET RESULTS ===\n")
print(classification_report(Y_dev, Y_pred, target_names=mlb.classes_, zero_division=0))

=== DEV SET RESULTS ===

                             precision    recall  f1-score   support

       Behavioral Breakdown       0.00      0.00      0.00         2
   Cognitive Bias Formation       0.00      0.00      0.00         0
      Decision Under Duress       0.00      0.00      0.00         0
    Emotional Dysregulation       1.00      1.00      1.00         1
      Encoding Under Stress       0.00      0.00      0.00         1
     Fear & Threat Response       0.00      0.00      0.00         0
          Flow & Absorption       0.00      0.00      0.00         2
       Habit & Automaticity       0.00      0.00      0.00         1
         Identity Anchoring       0.50      1.00      0.67         1
       Meaning Construction       0.00      0.00      0.00         0
   Peak Performance Ceiling       0.00      0.00      0.00         1
      Self-Concept Updating       0.00      0.00      0.00         3
Stress & Arousal Regulation       0.00      0.00      0.00         1
           Threat Appraisal       0.00      0.00      0.00         1
    Traumatic Consolidation       1.00      0.50      0.67         2

                  micro avg       0.38      0.19      0.25        16
                  macro avg       0.17      0.17      0.16        16
               weighted avg       0.22      0.19      0.19        16
                samples avg       0.33      0.19      0.24        16

In [11]:
# Run a real prediction

def classify_document(text):
    vec = model.encode([text])
    pred = clf.predict(vec)
    labels = mlb.inverse_transform(pred)[0]

    # Organize by layer
    memory_labels = ["Encoding Under Stress", "Traumatic Consolidation", "Identity Anchoring"]
    belief_labels = ["Cognitive Bias Formation", "Self-Concept Updating", "Threat Appraisal", "Meaning Construction"]
    emotion_labels = ["Stress & Arousal Regulation", "Fear & Threat Response", "Flow & Absorption", "Emotional Dysregulation"]
    behavior_labels = ["Decision Under Duress", "Habit & Automaticity", "Peak Performance Ceiling", "Behavioral Breakdown"]

    result = {
        "memory":   [l for l in labels if l in memory_labels],
        "belief":   [l for l in labels if l in belief_labels],
        "emotion":  [l for l in labels if l in emotion_labels],
        "behavior": [l for l in labels if l in behavior_labels]
    }
    return result

# Test it
doc = "CIA operatives in isolation experiments reported fragmentation of self-narrative and loss of temporal anchoring"
result = classify_document(doc)

print("INPUT:", doc)
print("\nIDENTITY STATE POSITION:")
for layer, label in result.items():
    print(f"  {layer.upper():10} → {label}")

INPUT: CIA operatives in isolation experiments reported fragmentation of self-narrative and loss of temporal anchoring

IDENTITY STATE POSITION:
  MEMORY     → ['Identity Anchoring']
  BELIEF     → []
  EMOTION    → ['Emotional Dysregulation']
  BEHAVIOR   → ['Behavioral Breakdown']

In [12]:
!pip install anthropic -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 753.6/753.6 kB 7.9 MB/s eta 0:00:00

In [13]:
import anthropic
import pandas as pd
import json
import time

client = anthropic.Anthropic(api_key=userdata.get('ANTHROPIC_API_KEY'))

# Load the unlabeled corpus
df_corpus = pd.read_csv("02_data/elara_corpus_raw.csv")
# Only label docs that don't already have labels
df_unlabeled = df_corpus[df_corpus["source"] != "seed"].copy()
print(f"Documents to label: {len(df_unlabeled)}")

SYSTEM_PROMPT = """You are ELARA, a classifier that maps research documents
onto an Identity State Engine — a 4-layer model of how human identity forms,
breaks, and recovers under pressure.

For each document assign exactly ONE label per layer from this taxonomy:

MEMORY: Encoding Under Stress | Traumatic Consolidation | Identity Anchoring
BELIEF: Cognitive Bias Formation | Self-Concept Updating | Threat Appraisal | Meaning Construction
EMOTION: Stress & Arousal Regulation | Fear & Threat Response | Flow & Absorption | Emotional Dysregulation
BEHAVIOR: Decision Under Duress | Habit & Automaticity | Peak Performance Ceiling | Behavioral Breakdown

Respond ONLY with valid JSON. No preamble. No explanation. Example:
{"memory": "Encoding Under Stress", "belief": "Threat Appraisal", "emotion": "Fear & Threat Response", "behavior": "Decision Under Duress"}"""

results = []
errors = 0

for i, row in df_unlabeled.iterrows():
    try:
        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=150,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": row["text"][:800]}]
        )

        label_json = json.loads(response.content[0].text)
        results.append({
            "text": row["text"],
            "source": row["source"],
            "memory": label_json.get("memory", ""),
            "belief": label_json.get("belief", ""),
            "emotion": label_json.get("emotion", ""),
            "behavior": label_json.get("behavior", "")
        })

        if i % 50 == 0:
            print(f"✓ Labeled {len(results)} documents...")

        time.sleep(0.3)  # rate limit buffer

    except Exception as e:
        errors += 1
        if errors < 5:
            print(f"Error on doc {i}: {e}")

df_labeled = pd.DataFrame(results)
df_labeled.to_csv("02_data/elara_labeled.csv", index=False)
print(f"\n✓ Labeled: {len(df_labeled)} documents")
print(f"✗ Errors: {errors}")
df_labeled.head(3)

Documents to label: 897

/tmp/ipykernel_4891/2166473331.py:33: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  response = client.messages.create(

✓ Labeled 31 documents...
Error on doc 53: Expecting value: line 1 column 1 (char 0)
Error on doc 56: Expecting value: line 1 column 1 (char 0)
Error on doc 59: Expecting value: line 1 column 1 (char 0)
Error on doc 64: Expecting value: line 1 column 1 (char 0)
✓ Labeled 71 documents...
✓ Labeled 114 documents...
✓ Labeled 198 documents...
✓ Labeled 242 documents...
✓ Labeled 284 documents...
✓ Labeled 329 documents...
✓ Labeled 367 documents...
✓ Labeled 407 documents...
✓ Labeled 450 documents...
✓ Labeled 490 documents...
✓ Labeled 533 documents...
✓ Labeled 576 documents...
✓ Labeled 618 documents...
✓ Labeled 659 documents...
✓ Labeled 699 documents...
✓ Labeled 739 documents...

✓ Labeled: 755 documents
✗ Errors: 142

,text,source,memory,belief,emotion,behavior
0,1. Psychiatry Res. 2026 Apr 30;362:117211. doi...,PubMed,Traumatic Consolidation,Self-Concept Updating,Emotional Dysregulation,Behavioral Breakdown
1,"Sipahimalani G(1), Sauvet F(2), Quiquempoix M(...",PubMed,Encoding Under Stress,Threat Appraisal,Stress & Arousal Regulation,Decision Under Duress
2,Author information:\n(1)Department of Psychiat...,PubMed,Encoding Under Stress,Threat Appraisal,Stress & Arousal Regulation,Peak Performance Ceiling

In [14]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd

# Load labeled data
df_labeled = pd.read_csv("02_data/elara_labeled.csv")

# Combine seed labels into same format
df_seed = pd.read_csv("02_data/seed_corpus.csv")
import ast
df_seed["labels"] = df_seed["labels"].apply(ast.literal_eval)
df_seed[["memory","belief","emotion","behavior"]] = pd.DataFrame(
    df_seed["labels"].tolist(), index=df_seed.index)

# Merge seed + auto-labeled
df_all = pd.concat([
    df_labeled[["text","memory","belief","emotion","behavior"]],
    df_seed[["text","memory","belief","emotion","behavior"]]
], ignore_index=True).dropna()

print(f"Total labeled documents: {len(df_all)}")

# Re-embed all documents
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("allenai-specter")
X_all = model.encode(df_all["text"].tolist(), show_progress_bar=True)

# Build multi-label target — all 4 layers as one label set
df_all["all_labels"] = df_all.apply(
    lambda r: [r["memory"], r["belief"], r["emotion"], r["behavior"]], axis=1)

mlb = MultiLabelBinarizer()
Y_all = mlb.fit_transform(df_all["all_labels"])

# 60/20/20 split
X_train, X_temp, Y_train, Y_temp = train_test_split(
    X_all, Y_all, test_size=0.4, random_state=42)
X_dev, X_test, Y_dev, Y_test = train_test_split(
    X_temp, Y_temp, test_size=0.5, random_state=42)

print(f"Train: {len(X_train)} · Dev: {len(X_dev)} · Test: {len(X_test)}")

# Train
clf = OneVsRestClassifier(LogisticRegression(max_iter=1000))
clf.fit(X_train, Y_train)
print("\n✓ Model trained on full corpus")

Total labeled documents: 775

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/allenai-specter
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/25 [00:00<?, ?it/s]

Train: 465 · Dev: 155 · Test: 155

✓ Model trained on full corpus

In [15]:
sY_pred = clf.predict(X_dev)
print("=== ELARA DEV SET RESULTS ===\n")
print(classification_report(
    Y_dev, Y_pred,
    target_names=mlb.classes_,
    zero_division=0))

# Save model
import pickle
with open("04_training/elara_classifier.pkl", "wb") as f:
    pickle.dump(clf, f)
with open("04_training/elara_mlb.pkl", "wb") as f:
    pickle.dump(mlb, f)

print("\n✓ Model saved to 04_training/")

=== ELARA DEV SET RESULTS ===

                             precision    recall  f1-score   support

       Behavioral Breakdown       0.70      0.66      0.68        56
   Cognitive Bias Formation       0.25      0.07      0.11        14
      Decision Under Duress       0.44      0.38      0.41        29
    Emotional Dysregulation       0.57      0.65      0.60        40
      Encoding Under Stress       0.43      0.35      0.39        17
     Fear & Threat Response       0.75      0.53      0.62        17
          Flow & Absorption       0.62      0.57      0.59        14
       Habit & Automaticity       0.55      0.60      0.58        43
         Identity Anchoring       0.75      0.79      0.77        72
       Meaning Construction       0.50      0.31      0.38        13
   Peak Performance Ceiling       0.60      0.44      0.51        27
      Self-Concept Updating       0.73      0.82      0.77        91
Stress & Arousal Regulation       0.74      0.67      0.70        84
           Threat Appraisal       0.64      0.57      0.60        37
    Traumatic Consolidation       0.68      0.68      0.68        66

                  micro avg       0.66      0.64      0.65       620
                  macro avg       0.60      0.54      0.56       620
               weighted avg       0.65      0.64      0.64       620
                samples avg       0.67      0.64      0.64       620


✓ Model saved to 04_training/

In [23]:
app_code = '''
import gradio as gr
import anthropic
import pandas as pd
import numpy as np
import os
import ast
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# ── Load data ──────────────────────────────────────────────────────────────
df = pd.read_csv("02_data/elara_labeled.csv")
df = df[df["text"].notna()].reset_index(drop=True)

embeddings = np.load("03_features/specter_embeddings_full.npy")

model = SentenceTransformer("allenai-specter")
client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))

LAYERS = ["memory", "belief", "emotion", "behavior"]

LAYER_COLORS = {
    "memory": "#3B82F6",
    "belief": "#F59E0B",
    "emotion": "#EF4444",
    "behavior": "#10B981"
}

# ── Retrieval ───────────────────────────────────────────────────────────────
def retrieve(query, top_k=5, filter_layer=None, filter_label=None):
    q_vec = model.encode([query])
    sims = cosine_similarity(q_vec, embeddings)[0]
    top_idx = sims.argsort()[::-1]

    results = []
    for i in top_idx:
        row = df.iloc[i]
        if filter_layer and filter_label:
            if row.get(filter_layer, "") != filter_label:
                continue
        results.append({
            "text": row["text"],
            "memory": row.get("memory", ""),
            "belief": row.get("belief", ""),
            "emotion": row.get("emotion", ""),
            "behavior": row.get("behavior", ""),
            "score": float(sims[i])
        })
        if len(results) >= top_k:
            break
    return results

# ── Chat ────────────────────────────────────────────────────────────────────
def chat(message, history):
    docs = retrieve(message, top_k=5)

    context = ""
    for i, d in enumerate(docs):
        context += f"""
Document {i+1}:
{d["text"][:600]}

Identity State Position:
  MEMORY   → {d["memory"]}
  BELIEF   → {d["belief"]}
  EMOTION  → {d["emotion"]}
  BEHAVIOR → {d["behavior"]}
---"""

    system = """You are ELARA, an intelligence analyst trained on declassified
CIA and DARPA research on human consciousness, identity, and performance.

You answer questions using the retrieved research documents below as your
primary source. Always reference the Identity State Layer (memory/belief/
emotion/behavior) when explaining findings. Be precise, analytical, and
treat the user as a serious researcher.

Retrieved documents:
""" + context

    messages = []
    for h in history:
        messages.append({"role": "user", "content": h[0]})
        messages.append({"role": "assistant", "content": h[1]})
    messages.append({"role": "user", "content": message})

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1000,
        system=system,
        messages=messages
    )

    return response.content[0].text

# ── Explorer ────────────────────────────────────────────────────────────────
def get_labels_for_layer(layer):
    return ["All"] + sorted(df[layer].dropna().unique().tolist())

def explore(layer, label, search_query):
    filtered = df.copy()

    if label and label != "All":
        filtered = filtered[filtered[layer] == label]

    if search_query:
        mask = filtered["text"].str.contains(search_query, case=False, na=False)
        filtered = filtered[mask]

    filtered = filtered.head(20)

    rows = ""
    for _, row in filtered.iterrows():
        rows += f"""
<div style="border:1px solid #e5e7eb;border-radius:8px;padding:14px;margin-bottom:10px;background:#fff">
  <div style="font-size:13px;line-height:1.6;color:#111;margin-bottom:10px">{row["text"][:400]}...</div>
  <div style="display:flex;gap:8px;flex-wrap:wrap">
    <span style="background:#EFF6FF;color:#3B82F6;padding:2px 8px;border-radius:4px;font-size:11px;font-family:monospace">MEMORY: {row.get("memory","—")}</span>
    <span style="background:#FFFBEB;color:#D97706;padding:2px 8px;border-radius:4px;font-size:11px;font-family:monospace">BELIEF: {row.get("belief","—")}</span>
    <span style="background:#FEF2F2;color:#EF4444;padding:2px 8px;border-radius:4px;font-size:11px;font-family:monospace">EMOTION: {row.get("emotion","—")}</span>
    <span style="background:#F0FDF4;color:#10B981;padding:2px 8px;border-radius:4px;font-size:11px;font-family:monospace">BEHAVIOR: {row.get("behavior","—")}</span>
  </div>
</div>"""

    if not rows:
        rows = "<div style='color:#6b7280;padding:20px'>No documents found.</div>"

    return f"<div style='max-height:600px;overflow-y:auto'>{rows}</div>"

def update_labels(layer):
    labels = get_labels_for_layer(layer)
    return gr.Dropdown(choices=labels, value="All")

# ── Classify new doc ────────────────────────────────────────────────────────
def classify(text):
    if not text.strip():
        return "Enter a document to classify."

    import pickle
    try:
        with open("04_training/elara_classifier.pkl", "rb") as f:
            clf = pickle.load(f)
        with open("04_training/elara_mlb.pkl", "rb") as f:
            mlb = pickle.load(f)

        vec = model.encode([text])
        pred = clf.predict(vec)
        labels = mlb.inverse_transform(pred)[0]

        memory_labels = ["Encoding Under Stress","Traumatic Consolidation","Identity Anchoring"]
        belief_labels = ["Cognitive Bias Formation","Self-Concept Updating","Threat Appraisal","Meaning Construction"]
        emotion_labels = ["Stress & Arousal Regulation","Fear & Threat Response","Flow & Absorption","Emotional Dysregulation"]
        behavior_labels = ["Decision Under Duress","Habit & Automaticity","Peak Performance Ceiling","Behavioral Breakdown"]

        result = {
            "MEMORY":   [l for l in labels if l in memory_labels],
            "BELIEF":   [l for l in labels if l in belief_labels],
            "EMOTION":  [l for l in labels if l in emotion_labels],
            "BEHAVIOR": [l for l in labels if l in behavior_labels]
        }

        out = "## Identity State Position\\n\\n"
        for layer, lbls in result.items():
            out += f"**{layer}** → {lbls[0] if lbls else 'unclear'}\\n\\n"
        return out
    except Exception as e:
        return f"Classifier not loaded yet: {e}"

# ── UI ───────────────────────────────────────────────────────────────────────
css = """
#elara-header {
    background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
    padding: 24px 32px;
    border-radius: 12px;
    margin-bottom: 20px;
}
.tab-nav button { font-family: monospace; font-size: 13px; }
"""

with gr.Blocks(css=css, title="ELARA — Identity State Classifier") as demo:

    gr.HTML("""
    <div id="elara-header">
      <div style="color:#94a3b8;font-size:11px;letter-spacing:0.15em;font-family:monospace;margin-bottom:6px">
        ELARA · COGNITION RESEARCH CLASSIFIER · 2026
      </div>
      <div style="color:#f1f5f9;font-size:22px;font-weight:600;margin-bottom:4px">
        Identity State Engine
      </div>
      <div style="color:#64748b;font-size:13px;font-family:monospace">
        Declassified CIA · DARPA · PubMed · 880+ documents · 4-layer taxonomy
      </div>
    </div>
    """)

    with gr.Tabs():

        # Tab 1 — Chat
        with gr.Tab("💬 Research Chat"):
            gr.Markdown("Ask anything about the declassified research. ELARA retrieves relevant documents and answers through the identity state lens.")
            chatbot = gr.ChatInterface(
                fn=chat,
                examples=[
                    "What breaks first in the human mind under extreme duress?",
                    "How does the brain consolidate traumatic memory differently than normal memory?",
                    "What cognitive states precede total behavioral breakdown?",
                    "How do elite operators suppress fear to maintain performance?",
                ],
                title=""
            )

        # Tab 2 — Explorer
        with gr.Tab("🗂 Document Explorer"):
            gr.Markdown("Browse 880+ classified research documents filtered by identity state layer.")
            with gr.Row():
                layer_dd = gr.Dropdown(
                    choices=LAYERS,
                    value="memory",
                    label="Layer"
                )
                label_dd = gr.Dropdown(
                    choices=get_labels_for_layer("memory"),
                    value="All",
                    label="Label"
                )
                search_box = gr.Textbox(
                    placeholder="Search documents...",
                    label="Keyword search"
                )
            explore_btn = gr.Button("Search", variant="primary")
            results_html = gr.HTML()

            layer_dd.change(update_labels, inputs=layer_dd, outputs=label_dd)
            explore_btn.click(explore, inputs=[layer_dd, label_dd, search_box], outputs=results_html)

        # Tab 3 — Classify
        with gr.Tab("⚡ Classify a Document"):
            gr.Markdown("Paste any text — ELARA maps it to its position in identity space.")
            with gr.Row():
                with gr.Column():
                    input_text = gr.Textbox(
                        lines=8,
                        placeholder="Paste a research abstract, document excerpt, or any text...",
                        label="Input Document"
                    )
                    classify_btn = gr.Button("Classify →", variant="primary")
                with gr.Column():
                    output_md = gr.Markdown(label="Identity State Position")

            classify_btn.click(classify, inputs=input_text, outputs=output_md)

demo.launch()
'''

# Save the app
os.makedirs("/content/elara", exist_ok=True)
with open("/content/elara/app.py", "w") as f:
    f.write(app_code)

print("✓ app.py created")

✓ app.py created

In [24]:
requirements = """gradio>=4.0.0
anthropic
sentence-transformers
scikit-learn
pandas
numpy
"""

with open("/content/elara/requirements.txt", "w") as f:
    f.write(requirements)

print("✓ requirements.txt created")

✓ requirements.txt created

In [25]:
# Install HuggingFace hub
import numpy as np
!pip install huggingface_hub -q
from huggingface_hub import HfApi
from google.colab import userdata

HF_TOKEN = userdata.get('HF_TOKEN')
HF_USER = "LeiaAnapaula"
SPACE_NAME = "elara"

api = HfApi()

# Upload with the correct name the app expects
api.upload_file(
    path_or_fileobj="/content/elara/03_features/specter_embeddings.npy",
    path_in_repo="03_features/specter_embeddings_full.npy",
    repo_id=f"{HF_USER}/{SPACE_NAME}",
    repo_type="space",
    token=HF_TOKEN
)

print("✓ Uploaded as specter_embeddings_full.npy")
print("Space will restart automatically — check it in 1 minute")

# Upload app.py
api.upload_file(
    path_or_fileobj="/content/elara/app.py",
    path_in_repo="app.py",
    repo_id=f"{HF_USER}/{SPACE_NAME}",
    repo_type="space",
    token=HF_TOKEN
)

# Upload requirements.txt
api.upload_file(
    path_or_fileobj="/content/elara/requirements.txt",
    path_in_repo="requirements.txt",
    repo_id=f"{HF_USER}/{SPACE_NAME}",
    repo_type="space",
    token=HF_TOKEN
)

# Upload labeled data
api.upload_file(
    path_or_fileobj="/content/elara/02_data/elara_labeled.csv",
    path_in_repo="02_data/elara_labeled.csv",
    repo_id=f"{HF_USER}/{SPACE_NAME}",
    repo_type="space",
    token=HF_TOKEN
)

# Upload embeddings
api.upload_file(
    path_or_fileobj="/content/elara/03_features/specter_embeddings.npy",
    path_in_repo="03_features/specter_embeddings.npy",
    repo_id=f"{HF_USER}/{SPACE_NAME}",
    repo_type="space",
    token=HF_TOKEN
)

print(f"✓ Live at: https://huggingface.co/spaces/{HF_USER}/{SPACE_NAME}")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...es/specter_embeddings.npy: 100%|##########| 61.6kB / 61.6kB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

✓ Uploaded as specter_embeddings_full.npy
Space will restart automatically — check it in 1 minute

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.
No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...es/specter_embeddings.npy: 100%|##########| 61.6kB / 61.6kB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

✓ Live at: https://huggingface.co/spaces/LeiaAnapaula/elara